# dashboard/models.py

# Import Django's base model class
from django.db import models

# This file is where you define your database models for the 'dashboard' app.
# Currently, there are no models defined here because this app doesn't store its own data.
# Instead, it likely reads from models in other apps (e.g., 'player_profiles') to render charts and statistics.

# Example placeholder (auto-generated by Django):
# Create your models here.
