# Generated by Django 5.1.6 on 2025-04-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("height_in_inches", models.FloatField()),
                ("weight_in_pounds", models.FloatField()),
                ("position", models.CharField(max_length=50)),
                ("games_played", models.IntegerField()),
                ("minutes_played", models.FloatField()),
                ("field_goals_attempted", models.IntegerField()),
                ("three_point_field_goals_attempted", models.IntegerField()),
                ("free_throws_attempted", models.IntegerField()),
                ("steals", models.IntegerField()),
                ("blocks", models.IntegerField()),
                ("fouls", models.IntegerField()),
                (
                    "predicted_risk_label",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_injuries", models.IntegerField(default=0)),
                (
                    "most_common_injury",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="player_profiles.playerprofile",
                    ),
                ),
            ],
        ),
    ]
