# Generated by Django 5.1.6 on 2025-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="most_common_injury",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ankle", "Ankle"),
                    ("Pectoral", "Pectoral"),
                    ("Toe", "Toe"),
                    ("Back", "Back"),
                    ("Knee", "Knee"),
                    ("Finger", "Finger"),
                    ("Hamstring", "Hamstring"),
                    ("Groin", "Groin"),
                    ("Nose", "Nose"),
                    ("Wrist", "Wrist"),
                    ("Illnesses", "Illnesses"),
                    ("Thoracic", "Thoracic"),
                    ("Abdominal", "Abdominal"),
                    ("Adductor", "Adductor"),
                    ("Foot", "Foot"),
                    ("Calf", "Calf"),
                    ("Shoulder", "Shoulder"),
                    ("Hip", "Hip"),
                    ("Concussions", "Concussions"),
                    ("Neck", "Neck"),
                    ("Mouth", "Mouth"),
                    ("Quadriceps", "Quadriceps"),
                    ("Elbow", "Elbow"),
                    ("Achilles", "Achilles"),
                    ("Oblique", "Oblique"),
                    ("Eye", "Eye"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position",
            field=models.CharField(
                choices=[
                    ("Guard", "Guard"),
                    ("Forward", "Forward"),
                    ("Center", "Center"),
                ],
                max_length=50,
            ),
        ),
    ]
