"""
Django settings for play_analytics project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information, see:
- https://docs.djangoproject.com/en/5.1/topics/settings/
- https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# === BASE DIRECTORY CONFIG ===
# This is the base path of your Django project (e.g., /Users/yourname/playanalytics)
BASE_DIR = Path(__file__).resolve().parent.parent

# === SECURITY CONFIG ===
# Keep this key secret in production!
SECRET_KEY = 'django-insecure-ye8i4my(h$tkf&k4qfbls7mefw%^1sb-)=0tqhu*x*m-9l2zv7'

# Enable debug mode for development. Set to False in production.
DEBUG = True

# Hosts allowed to access this app (empty = localhost only)
ALLOWED_HOSTS = []


# === INSTALLED APPS ===
INSTALLED_APPS = [
    # Custom apps
    'player_profiles',     # Player stats and profile management
    'predictor',           # Injury risk prediction logic and views
    'dashboard',           # Dashboard UI for visual analytics
    'users',               # User registration and login system

    # Third-party packages
    'django_bootstrap5',   # Bootstrap 5 integration for forms/UI

    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


# === MIDDLEWARE ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# === ROOT URL CONFIGURATION ===
ROOT_URLCONF = 'play_analytics.urls'


# === TEMPLATE SETTINGS ===
# These tell Django where to look for HTML templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates folder
        'APP_DIRS': True,                  # Also look in each app's templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Required by Django auth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# === WSGI ENTRY POINT ===
WSGI_APPLICATION = 'play_analytics.wsgi.application'


# === DATABASE SETTINGS ===
# Using SQLite (default). For production, use PostgreSQL or MySQL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# === PASSWORD VALIDATORS ===
# Enforce password strength and security
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# === LOCALIZATION & TIMEZONE ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Vancouver'

USE_I18N = True   # Internationalization support
USE_TZ = True     # Enable timezone-aware datetimes


# === STATIC FILES (CSS, JS, IMAGES) ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Tell Django where to find your static assets
]


# === MEDIA FILES (User uploaded content) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# === DEFAULT PRIMARY KEY FIELD TYPE ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# === AUTH CONFIG ===
# Redirect unauthenticated users to login page
LOGIN_URL = '/users/login/'
